### PR TITLE
Corrected Compile Errors

### PR DESCRIPTION
**Pull request by hussam-apryse**
- Added `shx` package as a dev dependency so that copying in client start script works
- Added a boolean in Viewer.js to check if viewer instance loaded already in the useEffect hook
- Updated root rendering to use React 18
- Added LICENSE
- Updated package.json script to use `npm install` instead of `npm run setup`
- Updated README.md
- Added SampleHtmlProxy.png
- Added tools\copy-webviewer-files.js to the main root

### CODE REVIEW

**Review by maggievu-pdftron — COMMENTED** [review]
Overall looks good. Just have 1 comment to clean up the `tools/copy-webviewer-files.js` inside `client` as we're already using the same file at root level.

**Comment by hussam-apryse** [comment]
> Overall looks good. Just have 1 comment to clean up the `tools/copy-webviewer-files.js` inside `client` as we're already using the same file at root level.

Thanks for the feedback. I was thinking about that also, but I did not want to break the local postinstall script in the client's `package.json`. So I decided to err on the safe side and keep both. Generally, I try not remove any existing code when updating samples and I have cleared the reported issues.

So we have a few options:
1. Keep both files `tools/copy-webviewer-files.js` and `client/tools/copy-webviewer-files.js` and keep the postinstall script and allow it to work with `npm install` as is.
2. Remove both, the `client/tools/copy-webviewer-files.js` file and the postinstall script in `client/package.json`
3. Or if you any other approaches, let me know

**Comment by maggievu-pdftron** [comment]
> > Overall looks good. Just have 1 comment to clean up the `tools/copy-webviewer-files.js` inside `client` as we're already using the same file at root level.
> 
> Thanks for the feedback. I was thinking about that also, but I did not want to break the local postinstall script in the client's `package.json`. So I decided to err on the safe side and keep both. Generally, I try not remove any existing code when updating samples and I have cleared the reported issues.
> 
> So we have a few options:
> 
> 1. Keep both files `tools/copy-webviewer-files.js` and `client/tools/copy-webviewer-files.js` and keep the postinstall script and allow it to work with `npm install` as is.
> 2. Remove both, the `client/tools/copy-webviewer-files.js` file and the postinstall script in `client/package.json`
> 3. Or if you any other approaches, let me know

Addressed via Slack DM and reposted here for visibility. 

> When `npm i` is executed within the client directory, it still triggers the `postinstall` script at the root level. Therefore, the `postinstall` script in the client directory is unnecessary and can be removed. This has been consistently observed in my experience.

Let me know if there are any questions.

**Review by maggievu-pdftron — APPROVED** [review]
Approved

**Pull request merged**
